USE amsdb;

CREATE TABLE `ADMIN`
(
    `ADMIN_ID`    VARCHAR(20) NOT NULL,
    `ADMIN_NAME`    VARCHAR(20) NOT NULL,
 PRIMARY KEY ( `ADMIN_ID` )
);


CREATE TABLE `ATTENDANCE`
(
    `ONTIME_COUNT`    INTEGER NOT NULL,
    `LATE_COUNT`    INTEGER NOT NULL,
    `ABSENT_COUNT`    INTEGER NOT NULL,
    `ATTENDANCE_SCORE`    INTEGER NOT NULL,
    `OFFTIME_STATUS`    BOOLEAN NOT NULL,
    `EMP_NO`    VARCHAR(20) NOT NULL,
    FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(EMP_NO)
);


CREATE TABLE `부재`
(
    `EMP_NO`    VARCHAR(20) NOT NULL,
    `EMPTY_CATEGORY`    VARCHAR(20) NOT NULL,
    `EMPTY_NAME`    VARCHAR(20) NOT NULL,
    `EMPTY_DATE`    DATE NOT NULL,
    `EMPTY_CAUSE`    VARCHAR(255),
 PRIMARY KEY ( `EMP_NO`,`EMPTY_CATEGORY` )
);

ALTER TABLE `부재`
 ADD CONSTRAINT `부재_PK` PRIMARY KEY ( `EMP_NO`,`EMPTY_CATEGORY` );


CREATE TABLE `EMPLOYEE`
(
    `EMP_NO`    VARCHAR(20) NOT NULL,
    `EMP_ID`    VARCHAR(20) NOT NULL,
    `EMP_PW`    VARCHAR(20) NOT NULL,
    `EMP_NAME`    VARCHAR(20) NOT NULL,
    `PHONE`    VARCHAR(20) NOT NULL,
    `EMAIL`    VARCHAR(255) NOT NULL,
    `ADMIN_ID`    VARCHAR(20) NOT NULL,
    `POSITION_ID`    VARCHAR(20) NOT NULL,
 PRIMARY KEY ( `EMP_NO` )
);

ALTER TABLE `사원정보`
 ADD CONSTRAINT `사원정보_PK` PRIMARY KEY ( `EMP_NO` );


CREATE TABLE `직급`
(
    `POSITION_ID`    VARCHAR(20) NOT NULL,
    `POSITION_NAME`    VARCHAR(20) NOT NULL,
 PRIMARY KEY ( `POSITION_ID` )
);

ALTER TABLE `직급`
 ADD CONSTRAINT `직급_PK` PRIMARY KEY ( `POSITION_ID` );