USE amsdb;

CREATE TABLE `ADMIN`
(
    `ADMIN_ID`    VARCHAR(20) NOT NULL,
    `ADMIN_NAME`    VARCHAR(20) NOT NULL,
 PRIMARY KEY ( `ADMIN_ID` )
);

INSERT INTO ADMIN
	(ADMIN_ID, ADMIN_NAME) VALUES
    ('0','관리자'),
	('1','사원');


CREATE TABLE `ATTENDANCE`
(
    `ONTIME_COUNT`    INTEGER NOT NULL,
    `LATE_COUNT`    INTEGER NOT NULL,
    `ABSENT_COUNT`    INTEGER NOT NULL,
    `ATTENDANCE_SCORE`    INTEGER NOT NULL,
    `OFFTIME_STATUS`    BOOLEAN NOT NULL,
    `EMP_NO`    VARCHAR(20) NOT NULL,
    FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(EMP_NO)
);

/* INSERT INTO ATTENDANCE
	(ONTIME_COUNT, LATE_COUNT, ABSENT_COUNT, ATTENDANCE_SCORE, OFFTIME_STATUS,EMP_NO) VALUES
    (0,0,0,0,TRUE,1); */


CREATE TABLE `EMPTY_TABLE`
(
    `EMP_NO`    VARCHAR(20) NOT NULL,
    `EMPTY_CATEGORY`    VARCHAR(20) NOT NULL,
    `EMPTY_NAME`    VARCHAR(20) NOT NULL,
    `EMPTY_DATE`    DATE NOT NULL,
    `EMPTY_CAUSE`    VARCHAR(255),
 PRIMARY KEY ( `EMPTY_CATEGORY` ),
 FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEE(EMP_NO)
);

-- EMP_DATE 열에 중복을 방지하는 UNIQUE 제약 조건 추가
ALTER TABLE EMPTY_TABLE ADD CONSTRAINT UNIQUE (EMPTY_DATE);

/* INSERT INTO EMPTY_TABLE
	(EMP_NO, EMPTY_CATEGORY, EMPTY_NAME, EMPTY_DATE, EMPTY_CAUSE) VALUES
    ('001', '1', '연차', 'YYYY-MM-DD', NULL ); */
    

CREATE TABLE `COM_POSITION`
(
    `POSITION_ID`    VARCHAR(20) NOT NULL,
    `POSITION_NAME`    VARCHAR(20) NOT NULL,
 PRIMARY KEY ( `POSITION_ID` )
);

INSERT INTO COM_POSITION
	(POSITION_ID, POSITION_NAME) VALUES
    ('1' , '사장'),
    ('2' , '부장'),
    ('3' , '차장'),
    ('4' , '과장'),
    ('5' , '대리'),
    ('6' , '사원');

CREATE TABLE `EMPLOYEE`
(
    `EMP_NO`    VARCHAR(20) NOT NULL,
    `EMP_ID`    VARCHAR(20) NOT NULL,
    `EMP_PW`    VARCHAR(20) NOT NULL,
    `EMP_NAME`    VARCHAR(20) NOT NULL,
    `PHONE`    VARCHAR(20) NOT NULL,
    `EMAIL`    VARCHAR(255) NOT NULL,
    `ADMIN_ID`    VARCHAR(20) NOT NULL,
    `POSITION_ID`    VARCHAR(20) NOT NULL,
 PRIMARY KEY ( `EMP_NO` )
);

-- ADMIN_ID 와 POSITION_ID 외래키 지정
ALTER TABLE EMPLOYEE ADD FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ADMIN_ID);
ALTER TABLE EMPLOYEE ADD FOREIGN KEY (POSITION_ID) REFERENCES COM_POSITION(POSITION_ID);

-- EMP_ID 열에 중복을 방지하는 UNIQUE 제약 조건 추가
ALTER TABLE EMPLOYEE ADD CONSTRAINT UNIQUE (EMP_ID);

INSERT INTO EMPLOYEE 
	(EMP_NO, EMP_ID, EMP_PW, EMP_NAME, PHONE, EMAIL, ADMIN_ID, POSITION_ID)
    VALUES
    ('001', 'nunu1', '1101', 'YunSooBin', '010-1234-1234', 'soobinnunu1101@gamil.com', '1', '1');
